platform:
  type: CUDAPlatform
  parameters:
    name: nvidia_rtx_4090
dataset:
  type: PetDataset
  parameters:
    dataset_root: ./build/PetDataset
model_wrapper:
  type: TensorFlowPetDatasetMobileNetV2
  parameters:
    model_path: kenning:///models/classification/tensorflow_pet_dataset_mobilenetv2.h5
optimizers:
  - type: IREECompiler
    parameters:
      compiled_model_path: ./build/compiled_model.vmbf
      model_framework: keras
runtime:
  type: IREERuntime
  parameters:
    save_model_path: ./build/compiled_model.vmbf
report:
  parameter:
    measurements: ./build/pet-dataset-iree-cuda.json
