model_wrapper:
  type: MMPoseModelWrapper
  parameters:
    model_path: "https://download.openmmlab.com/mmpose/v1/projects/rtmposev1/rtmpose-m_simcc-body7_pt-body7-halpe26_700e-256x192-4d3e73dd_20230605.pth"
    keypoint_threshold: 0.3
dataset:
  type: VideoDataset
  parameters:
    video_file_path: /dev/video0
    input_memory_layout: NCHW
    dataset_root: .
    download_dataset: false
    input_width: 256
    input_height: 192
    split_fraction_test: 1
