platform:
  type: LocalPlatform
model_wrapper:
  type: TensorFlowPetDatasetMobileNetV2
  parameters:
    model_path: kenning:///models/classification/tensorflow_pet_dataset_mobilenetv2.h5
dataset:
  type: PetDataset
  parameters:
    dataset_root: build/PetDataset
optimizers:
- type: TVMCompiler
  parameters:
    compiled_model_path: ./build/compiled-model.tar
    model_framework: keras
report:
  type: MarkdownReport
  parameters:
    measurements: ./build/pet-dataset-tvm-cfg.json
    report_path: ./build/classification-report/report.md
    report_name: Classification on Pet Dataset using TVM
    report_types:
      - performance
      - classification
