model_wrapper:
  type: kenning.modelwrappers.instance_segmentation.yolact.YOLACT
  parameters:
    model_path: kenning:///models/instance_segmentation/yolact.onnx
dataset:
  type: kenning.datasets.open_images_dataset.OpenImagesDatasetV6
  parameters:
    dataset_root: ./build/OpenImagesDatasetV6
    inference_batch_size: 1
    task: instance_segmentation
optimizers:
  - type: kenning.optimizers.tflite.TFLiteCompiler
    parameters:
      target: default
      compiled_model_path: ./build/yolact.tflite
      use_tf_select_ops: true
runtime:
  type: kenning.runtimes.tflite.TFLiteRuntime
  parameters:
    save_model_path: ./build/yolact.tflite
report:
  parameters:
    measurements: ./build/yolact-tflite.json
    report_path: ./build/yolact-report/report.md
    report_name: YOLACT detection report
    root_dir: ./build/yolact-report
    img_dir: ./build/yolact-report/imgs
    report_types:
      - performance
      - detection