# This scenario demonstrates deployment of Anomaly Detection in time series on MAX32960 Evaluation Kit
# It provides two variants of execution - a deployment on an actual hardware, and simulation in Renode
# This scenario should be executed within kenning-zephyr-runtime project, with built evaluation app for
# TFLite Micro runtime:
#
# west build -p always -b max32690evkit/max32690/m4 app -- -DEXTRA_CONF_FILE="tflite.conf"
#
# A dataset used for evaluating the model
dataset:
    type: kenning.datasets.anomaly_detection_dataset.AnomalyDetectionDataset
    parameters:
        dataset_root: ./workspace/dataset
        csv_file: https://zenodo.org/records/8338435/files/data.csv
        split_fraction_test: 0.0005
        inference_batch_size: 1
        split_seed: 12345
# model wrapper for the VAE anomaly detection model
model_wrapper:
    type: kenning.modelwrappers.anomaly_detection.vae.PyTorchAnomalyDetectionVAE
    parameters:
        model_name: vae
        model_path: ./vae_small.pth
        encoder_layers: [16, 8]
        batch_norm: true
# run TFLite conversion from above PyTorch model to TFLite Flatbuffers
optimizers:
    - type: kenning.optimizers.tflite.TFLiteCompiler
      parameters:
          compiled_model_path: ./workspace/vae_small.tflite
          target: default
          inference_input_type: float32
          inference_output_type: float32

# Uncomment preferred variant of model deployment and evaluation

# this is a runtime that uses Renode simulation to evaluate the model
# it uses UART communication on /tmp/uart

runtime:
    type: kenning.runtimes.renode.RenodeRuntime
    parameters:
        runtime_binary_path: ./build/zephyr/zephyr.elf
        platform_resc_path: ./renode/scripts/max32690evkit.resc
        resc_dependencies:
            - ./build/max32690evkit.repl
        runtime_log_uart: /tmp/uart-log
        runtime_log_init_msg: "I: Inference server started"
        profiler_dump_path: ./build/profiler.dump
protocol:
    type: kenning.protocols.uart.UARTProtocol
    parameters:
        port: /tmp/uart
        baudrate: 9600
        endianness: little

# end of Renode-based evaluation

# this is a runtime that runs on the actual MAX32690 Evaluation Kit
# Path to the UART port is set to /dev/ttyUSB0, change it to appropriate path

# runtime:
#     type: kenning.runtimes.tflite.TFLiteRuntime
#     parameters: {}
# protocol:
#     type: kenning.protocols.uart.UARTProtocol
#     parameters:
#         port: /dev/ttyUSB0
#         baudrate: 9600
#         endianness: little

# end of hardware-based evaluation
